Update .gitlab-ci.yml
Ensembl/ensembl-web-tools-api pull request #5
Opened 2023-07-20 14:29 UTC by jyothishnt

https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2037

2023-07-20 16:10 UTC, kamaldodiya requested changes

2023-07-20 16:10 UTC, kamaldodiya commented on .gitlab-ci.yml
> +    - if: '$CI_DEPLOY_FREEZE == null && $CI_COMMIT_BRANCH == "k8s-migration"'
For testing the branch to be checked against CI_COMMIT_BRANCH should be the branch name, in this case it is ```k8s-tools-api```
```- if: '$CI_DEPLOY_FREEZE == null && $CI_COMMIT_BRANCH == "k8s-tools-api"'```
and it should be reverted to master/main before merging

2023-07-20 16:27 UTC, jyothishnt commented on .gitlab-ci.yml
> +    - if: '$CI_DEPLOY_FREEZE == null && $CI_COMMIT_BRANCH == "k8s-migration"'
```suggestion
    - if: '$CI_DEPLOY_FREEZE == null && $CI_COMMIT_BRANCH == "k8s-tools-api"'
```

2023-07-20 18:00 UTC, kamaldodiya commented
@veidenberg  The test cases are failing can you please have a look. 
https://gitlab.ebi.ac.uk/ensembl-web/ensembl-tools-api/-/jobs/1337209

2023-07-21 14:38 UTC, kamaldodiya approved these changes

2023-07-21 14:39 UTC, veidenberg approved these changes

2023-07-21 14:40 UTC, merged