Update branch default to main branch
Ensembl/ensembl-web-tools-api pull request #52
Opened 2024-10-15 12:44 UTC by Mehrnaz-Charkhchi

### Description
Replace dev branch with main in Tools API repo

### Related JIRA Issue(s)
[ENSWBSITES-2782](https://www.ebi.ac.uk/panda/jira/browse/ENSWBSITES-2782)

### Review App URL(s) 
http://__BRANCH_NAME_HERE__.review.ensembl.org

### Knowledge Base

### Example(s)

### Checklist

- [ ] Black formatting
- [ ] Tests

### Dependencies

2024-10-15 12:47 UTC, kamaldodiya requested changes
Shouldn't this PR be against main ?

2024-10-15 13:18 UTC, Mehrnaz-Charkhchi commented
> Shouldn't this PR be against main ?

@kamaldodiya I'm resolving all the conflicts here so yes it can be against main, I want to make sure dev branch isn't affecting deployments anymore.

2024-10-21 11:04 UTC, kamaldodiya reviewed
I think pipeline wise it looks good to me I checked it by simulating the pipeline in the gitlab and it is as expected. Ultimately we won't be able to ascertain until this gets merged to main and we have few pipelines run. 
Just one thing I would like to highlight is that readability ( understanding ) pipeline is bit difficult.
it would be good to have consistency across deploy job
for example . [here](https://github.com/Ensembl/ensembl-web-tools-api/blob/branch_name_update/.gitlab-ci.yml#L179-L180) the job extends from deploy-main and explicit about stage
where as it changes for deploy production job [here](https://github.com/Ensembl/ensembl-web-tools-api/blob/branch_name_update/.gitlab-ci.yml#L191) where the stage is inferred from the reply-main template.

2024-10-22 09:28 UTC, kamaldodiya commented
Also https://github.com/Ensembl/ensembl-web-tools-api/blob/branch_name_update/.gitlab-ci.yml#L183-L184
Here branch is already inferred in the deploy-main template

2024-10-22 09:29 UTC, kamaldodiya requested changes

2024-10-22 09:29 UTC, kamaldodiya commented on .gitlab-ci.yml
> +    - if: $CI_COMMIT_BRANCH == "main"
The main in already inferred via .deploy-main template. I think this is redundant.

2024-10-22 10:01 UTC, veidenberg commented
@Mehrnaz-Charkhchi this PR includes commits and changes that have already been merged. Can you rebase `branch_name_update` to the last commit in `dev` branch?

2024-10-22 11:50 UTC, Mehrnaz-Charkhchi commented
> @Mehrnaz-Charkhchi this PR includes commits and changes that have already been merged. Can you rebase `branch_name_update` to the last commit in `dev` branch?

@veidenberg I did explain during the code review it's ready to be merged to main I'm merging it to dev to check the pipeline one last time.

2024-10-22 15:37 UTC, kamaldodiya approved these changes

2024-10-23 08:35 UTC, merged